### PR TITLE
added three words

### PR DESCRIPTION
**Pull request by nromey**
two words in root, one in main

### CODE REVIEW

**Comment by amirsol81** [comment]
@nromey Please kindly copy your edits and paste them in the comments section. I really want to merge your commits now, but should see the modified words and your suggested modifications here. This way if I find a problem, we can fix it both faster and more easily.

**Comment by amirsol81** [comment]
> two words in root, one in main

But what are they? Please copy/paste them here.

**Comment by nromey** [comment]
Sorry about that.Will do that in future. I can include words and Pr number. In main abdl. In root Arpeggione Aasvogel On Jun 29, 2023, at 16:19, amirsol81 ***@***.***> wrote:﻿

two words in root, one in main

But what are they? Please copy/paste them here.

**Comment by nromey** [comment]
Added three more words.
shearling	``[.1Sir.0lIG]
gomphiasis	`[.1gam.0fY.0o.0sIs]
chaetiferous	`[1kIt.1If.xr.0xs]

**Comment by amirsol81** [comment]
@nromey Thanks. Looking at your changes, it seems that your strees markings need some modifications. For instance, gomphiasis should be corrected this way: `[.2gam.0fY.1o.0sXs]. That is, the major/primary stress falls on the third syllable, o, and the last syllable is written as .0sXs.
The same is true about chaetiferous. It should be written/corrected this way: [.0kX.1tI.0fx.0rxs].
Would you please correct them for submission?

**Comment by amirsol81** [comment]
@nromey Awesome! Could you also include your suggested corrections for Arpeggione and Aasvogel? It seems to me that they also need some modifications.

**Comment by nromey** [comment]
See last commit for detailed change log. Thanks for your guidance--I'm learning :).

**Comment by thunderdrop** [comment]
@amirsol81 the changes are in the pull request itself, why are you asking for them to be commented here? Are you having trouble reviewing the contents of the commits? Let me know if there's something I need to fix :)

**Comment by amirsol81** [comment]
@nromey Right, but commenting, I mean simply pasting them here, allows us to correct them faster if needed.

**Comment by thunderdrop** [comment]
@amirsol81 If you find something that needs discussion or correction, you can of course paste it in your comments. Contributors don't need to comment on their PR with the changes that are already in it, that's what commits are for :)

**Comment by amirsol81** [comment]
@nromey I merged them - thanks! A couple of notes:
1. pteromerhanophobia is transcribed this way, emphasizing the "pho" syllable: `[.2ter.0x.0mxr.2ha.nx.1fo.0bi.0x]. Your transcription emphasizis the "pter" syllable, which shouldn't receive primary stress.
2. In Main.dic, all transcriptions should be lowercase for consistency.
3. In Root, definitely use 0, 1 and 2 after the dots to indicate the level of syllable stress, with 1 indicating primary stress.
Thanks.

**Comment by amirsol81** [comment]
@thunderdrop Right! After so many commits, I'm still finding it difficult to view the contents of other members' commits 😀 . Guess I should mend my ways.

**Comment by thunderdrop** [comment]
@amirsol81 As in it's not working the way you expected, or you don't know how to do it?

**Comment by nromey** [comment]
Bi agree with my favorite linguist and stress manager 🤣😄😁  I think that adding a comment isn’t much to ask and allows me to learn all about these lovely syl-ah-bles. Thanks to you both for an awesome project and for allowing me to add words and things to the dictionary. I’m lots more confident w GitHub which is an extra bonus. Makes me want to come out of my shell a bit and add pull requests for other projects. Have a great day my friends. On Jun 30, 2023, at 03:09, amirsol81 ***@***.***> wrote:﻿
@nromey I merged them - thanks! A couple of notes:

pteromerhanophobia is transcribed this way, emphasizing the "pho" syllable: `[.2ter.0x.0mxr.2ha.nx.1fo.0bi.0x]. Your transcription emphasizis the "pter" syllable, which shouldn't receive primary stress.
In Main.dic, all transcriptions should be lowercase for consistency.
In Root, definitely use 0, 1 and 2 after the dots to indicate the level of syllable stress, with 1 indicating primary stress.
Thanks.

**Comment by nromey** [comment]
Would you like me to fix pteromerhanophobia?  No issue if I need to do that. Also sorry about the rogue capital letter in main, will review my changes and fix caps when I find them. Finally re stress, I continue to struggle about primary and secondary stress. I try to both repeat the word out loud, trying to figure where stress needs to go, and throwing the transcription into elocutor   If it sounds right in the demo output, I go with it, so I’m guessing sometimes these syllable queries can and are subjective sometimes. Thanks for the guidance. Let me know how I can improve as that’s how I learn the most.

Noel

**Comment by nromey** [comment]
Last message from me. I’m not sure what client you use, but I find it’s cool, especially in the desktop app, to open up a conflicted file in notepad plus plus and read changes it annotates in the file. Saved my bacon yesterday though it was probably quite confusing for the reviewer as I kept having to open and close poll requests because I couldn’t figure out how to resolve my conflict and get all of my files up-to-date. I do think that I haven’t figured out as well. We shall see. Thanks again.

**Comment by amirsol81** [comment]
@nromey First and foremost, you're doing a great job! Your comments, commits and viewpoints are all appreciated here.
As for pteromerhanophobia, I've fixed it and it's already in the project.

**Comment by amirsol81** [comment]
@nromey Stress manager! 🤣🤣🤣 Your compliment really made my day!

**Comment by amirsol81** [comment]
@nromey As for primary/secondary/tertiary stress patterns, let's take pteromerhanophobia as an example.
I think, and this is just my understanding, that specifying the primary stress, I mean the syllable which should be stressed in a word, is easier than other stress-receiving syllables. With this word, it follows the general rule in English that words containing -phobia are stressed where the pho- syllable starts. For words which are part of dictionaries - I mean Merriam-Webster, Dictionary.com, Cambridge, etc., the primary stress can be determined by looking at their transcription. I know it's easier said than done, but the more you do this, the better/quicker you can determine the stress markers.

**Pull request merged**
