### PR TITLE
Update ENURoot.dic" Added multiple entries including Kbin, Renault, and multiple additional proper names

### PR DESCRIPTION
**Pull request by PratikP1**
Following additions were made.

renault	`[.0rE.1no]
pratik	`[.2prH.1tik]
ze	`[.1ze]
kbin	`[.1ke.0bIn]
kiran	`[.1ki.0rHn]
yevgeniy	`[.1yEv.0gEni]
prigozhin	`[.0prI.1go.0Zinn]
vaishali	`[.0vHy.1Sa.0li]
vishal	`[.0vi.1Sal]
jaimin	`[.1JHy.2mIn]
arjun	`[01Hr.0Jun]
prashant	`[.2prH.1Sant]
unnati	`[.1uNH.2ti]
siddhi	`[.1sI?.0Di]
riddhi	`[.1rI?.0Di]

### CODE REVIEW

**Comment by amirsol81** [comment]
@PratikP1 Thanks! I want to merge this but:
1. We already have renault in the form of `[.0rX.1nclt], which is the Anglicized form, and yours is the original French pronunciation: https://www.dictionary.com/browse/renault
2. We also have prigozhin in the form of the more Anglicized [.0prX.1go.0ZXn].
3. Finally, since ze is a 2-letter word, I'm a bit worried about altering it in Root as it might addversely affect other words. Would you please check this one more thoroughly or perhaps scrap it for now?
I'd appreciate it if you remove the first two words, or, if you don't mind, I can do that.
Thanks again.

**Comment by PratikP1** [comment]
I personally prefer to have popular names and brands be pronounced in ways that original language pronunciations are. Renault is pronounced the French way even by most car people I have recently heard. It’s the same with Prigozhin. However, if there is a strong preference to keep them Anglicized, I’m happy to take them out. I’ll remove “ze” as well. I meant to remove it in favor of keeping it in my personal dictionary.

**Comment by amirsol81** [comment]
@PratikP1 You are right. However, this opens up a pandora's box and we have to deal with word like Adidas yet again! As such, we came to the conclusion, a long while ago, to keep these as Anglicized as possible. Even Renault once was altered to reflect your suggestion and I prefer it myself, but it was reverted.

**Comment by PratikP1** [comment]
@amirsol81 

I removed three words including Renault, Prigozhin, and ze. Thanks for letting me know about the history.

**Comment by amirsol81** [comment]
@PratikP1 Thanks. I just pushed it and, in a newer commit, made minor changes to a few of the pronunciations.

**Pull request merged**
