### PR TITLE
Multiple commits with NPR station names

### PR DESCRIPTION
**Pull request by nromey**
Several ommits including adding all known NPR stations that were mispronounced to main.

### CODE REVIEW

**Comment by amirsol81** [comment]
@nromey Thanks for the commits! I want to merge them, but Github is telling me that there's a conflict, and it's finding fault with ENUmain.dic. Don't know what's causing that, but it's suggesting that I not include ENUmain.dic for now. I'm a bit confused as I'm not a pro Github geek <smile>. @thunderdrop @ultrasound1372 might be able to help.

**Comment by nromey** [comment]
Well. I did most of the work in main. I’m not sure. I’d have to check the comparisons and I’m not a GitHub geek either. Sorry I screwed it up lol. On Jun 28, 2023, at 16:07, amirsol81 ***@***.***> wrote:﻿
@nromey Thanks for the commits! I want to merge them, but Github is telling me that there's a conflict, and it's finding fault with ENUmain.dic. Don't know what's causing that, but it's suggesting that I not include ENUmain.dic for now. I'm a bit confused as I'm not a pro Github geek . @thunderdrop @ultrasound1372 might be able to help.

**Comment by amirsol81** [comment]
No problem at all - this is not uncommon.
I took a look at ENUmain via the Github editor and it seems that a couple of lines have a strange format. So could you please take a look?

**Comment by nromey** [comment]
Sure. On Jun 28, 2023, at 16:19, amirsol81 ***@***.***> wrote:﻿
No problem at all - this is not uncommon.
I took a look at ENUmain via the Github editor and it seems that a couple of lines have a strange format. So could you please take a look?

**Comment by nromey** [comment]
Give this a whirl. I think that now there are four commits in this pull if I'm reading it right. The fourth one fixes the bunged up file. And wow, I just found a word to fix, bunged--wonder if that's a real word lol.

**Comment by nromey** [comment]
I didn't know that as I continue to make more changes, it all goes under my main pull request. Cool. It's now got 5 total commits. I hope this doesn't screw thiings up/you can get this to work.

**Pull request closed without merging**
