### PR TITLE
;removed one word and added two others, please read description

### PR DESCRIPTION
**Pull request by nromey**
tweeked advertisement again. It is more true to form if we leave it the way Eloquence was created :). Added Blytheville--yes there's a town that pronounces it this way. Added remembrall from Harry Potter
Also, I added the following:
Epicaricacy	`[1Ep.0xk.0xr.1Ik.0kx.2si]
This is a real word and I'm not sure if I've got the syllables correct. Please verify.

### CODE REVIEW

**Comment by nromey** [comment]
Sorry I added three words, removed one.

**Comment by amirsol81** [comment]
@nromey Thanks for your additions and commits! I then made a few corrections to them in a newer commit, so you may want to grab the newer ENURoot for comparison. A couple of notes:
1. Two of the words added to Root were capitalized. Words in Root shouldn't be capitalized because they will be rejected by the synthesizer. So make all words lowercase there.
2. The replacement for "epicaricacy" had two syllables beginning with .1. Since .1 indicates the primary stress, words should contain one of them because Eloquence will pronounce them strangely especially in continuous reading. As you know, in English words have one syllable carrying the primary stress, so here the rules work hand in hand. Here epicaricacy should be transcribed this way: `[2E.0pX.0kx.1rI.0kx.0si]
Looking forward to your upcoming commits.

**Comment by nromey** [comment]
Hey cool. Thanks for fixing things and guiding me.  Sorry about that capitalization thing.  I knew, but forgot this time. Continue to love learning.

 

NER

**Comment by amirsol81** [comment]
@nromey You're most welcome. Way to go!

**Pull request merged**
