### PR TITLE
Eloq ENU Dics - Jul 17

### PR DESCRIPTION
**Pull request by amirsol81**
New words added to ENURoot:
codicillary ->  `[.2ka.0FX.1sI.0lxr.0i]

codrive ->  `[.2ko.1drYv]

codrove ->  `[.2ko.1drov]

codriven ->  `[.2ko.1drI.0vXn]

coelomata ->  `[.0sX.1lo.0mE0Fx]

centralised -> `[.1sEn.0trx.2lYzd]

centralising -> `[.1sEn.0trx.2lY.0zIG]
# The last two, British spellings, were added to resolve a conflict with a previously added word: centralis -> `[.2sEn.1tre.0lXs]. fovea centralis. noun.  A small depression near the center of the retina, constituting the area of most acute vision.
pinata -> `[.0pi.1nya.0Fx]

piñata ->  `[.0pi.1nya.0Fx]

poptastic ->  `[.0pap.1tA.0stXk]

New word added to ENUmain:
emojipedia ->  `[.0X.2mo.0Ji.1pi.0Fi.0x]

### CODE REVIEW

**Comment by amirsol81** [comment]
Guess I finally managed to do it <smile>! In the meantime, my Collaborator status was lost. Any chance of restoring it?

**Comment by amirsol81** [comment]
It seems that my Collaborator status has been restored. Hurrah!

**Comment by thunderdrop** [comment]
This has been merged and all files are up to date as of this PR. As you *are* a collaborator, please commit and push future changes directly to the master branch from your local copy, and write what they are in your commit message. Thanks!

Peregryn

**Comment by amirsol81** [comment]
Thanks, will do that.

Cheers,

Amir

**Pull request merged**
